steps:
  - id: 'Install npm packages in vue'
    dir: led8vue
    name: 'node:12.9-buster'
    args: ['npm', 'install']
  - id: 'Install npm packages in functions'
    dir: functions
    name: 'node:12.9-buster'
    args: ['npm', 'install']
  - id: 'Install vue/cli'
    name: 'node:12.9-buster'
    args: ['yarn', 'global', 'add', '@vue/cli']
  - id: 'Build App'
    dir: led8vue
    name: 'node:12.9-buster'
    args: ['yarn', 'build']
    env:
    - 'VUE_APP_API_KEY=$VUE_APP_API_KEY'
    - 'VUE_APP_APP_ID=$VUE_APP_APP_ID'
    - 'VUE_APP_AUTH_DOMAIN=$VUE_APP_AUTH_DOMAIN'
    - 'VUE_APP_DATABASE_URL=$VUE_APP_DATABASE_URL'
    - 'VUE_APP_MESSAGING_SENDER_ID=$VUE_APP_MESSAGING_SENDER_ID'
    - 'VUE_APP_PROJECT_ID=$VUE_APP_PROJECT_ID'
    - 'VUE_APP_STORAGE_BUCKET=$VUE_APP_STORAGE_BUCKET'
  - id: "Fireabse Target apply"
    name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['target', 'apply', 'hosting', '$TARGET_SITE_NAME', '$TARGET_SITE_NAME', '--project', '$PROJECT_ID']
  - id: "Deploy to Firebase"
    name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID']
